### PR TITLE
Feat/data fairness simplification

### PR DESCRIPTION
**Pull request by fabrizio-credo**
## Describe your changes
Extracted run_cv and get demo_parity from data fairness

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have built basic tests for new functionality (particularly new evaluators)
- [ ] If new libraries have been added, I have checked that [readthedocs](https://readthedocs.org/projects/credoai-lens/) API documentation is constructed correctly
- [ ] Will this be part of a major product update? If yes, please write one phrase about this update.

## Extra-mile Checklist
- [ ] I have thought expansively about edge cases and written tests for them

### CODE REVIEW

**Review by IanAtCredo — CHANGES_REQUESTED** [review]
These seems like a WIP.

The goal of the helper functions is so we can look through them (or metrics) and understand what the evaluator does. So things like `_make_pipe` shouldn't be there and aspects of the other gigantic functions should be better modularized.

I moved `_make_pipe` into a FeatureInferenceAttacker class (I liked that description of it). But other functionality still seems needlessly complicated. `assess_balance_metrics` is a prime offender.

Did you not included functions like `calculate_mutual_information` because it seemed dependent on too many underlying arguments?

**Comment by fabrizio-credo** [comment]
In general I was thinking about what functions to extract in terms of topic/re-usability. The inferenceattack one seemed to be a good candidate for an external method used by data fairness. The other methods seemed more connected to the class function itself rather than stuff to be re-used elsewhere, therefore I left it in. Agreed that there can be more simplification.

**Comment by IanAtCredo** [comment]
> In general I was thinking about what functions to extract in terms of topic/re-usability. The inferenceattack one seemed to be a good candidate for an external method used by data fairness. The other methods seemed more connected to the class function itself rather than stuff to be re-used elsewhere, therefore I left it in. Agreed that there can be more simplification.

I think there are a few things here. Reusability is one, for sure. But even if functionality is _only_ used by one evaluator, the fact that it is buried in the class makes it difficult to document. Let's briefly sync later today on what we want/need from further simplification (if any)

**Review by IanAtCredo — APPROVED** [review]
lg

**Pull request merged**
